seminars/seminars_project/_2_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('choice/', views.choice, name='choice'),
    path('cube/', views.cube, name='cube'),
    path('rand100/', views.rand100, name='rand100'),
    path('articles/<int:author_id>', views.get_articles, name='articles'),
    path('article/<int:article_id>', views.get_article, name='article'),
    path('game/', views.game, name='game'),
    path('addauthor/', views.add_author, name='addauthor'),
    path('addarticle/', views.add_article, name='addarticle'),
    path('article_with_comment/<int:article_id>', views.comment_form, name='article_with_comment'),
]

seminars/seminars_project/online_store/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('orders/<int:client_id>', views.get_orders, name='orders'),
    path('client/<int:client_id>/items/', views.list_client_items, name='list_client_items'),
path('add_image_product/<int:product_id>', views.add_image_product, name='add_image_product'),
]

seminars/seminars_project/seminars_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sem_1_app.urls')),
    path('2/', include('_2_app.urls')),
    path('hw_1/', include('_hw_1_app.urls')),
    path('online_store/', include('online_store.urls')),

]

seminars/seminars_project/online_store/models.py
from django.db import models
from django.utils import timezone


class Client(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    date_registered = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()
    added_date = models.DateTimeField(default=timezone.now)
    photo = models.ImageField(upload_to='product_photos/', blank=True)

    def __str__(self):
        return self.name


class Order(models.Model):
    customer = models.ForeignKey(Client, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='OrderItem')
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    date_ordered = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Order #{self.pk} for {self.customer.name}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.quantity}x {self.product.name} in Order #{self.order.pk} ({self.order.customer.name})"

seminars/seminars_project/online_store/forms.py
from online_store import models
from django import forms


class AddImageProduct(forms.Form):
    photo = forms.ImageField()

seminars/seminars_project/online_store/views.py
from django.core.files.storage import FileSystemStorage

from . import forms
from django.shortcuts import render, get_object_or_404
from .models import *
from datetime import datetime, timedelta


def get_orders(request, client_id):

    client = get_object_or_404(Client, pk=client_id)
    orders = client.order_set.all()

    context = {
        'title': 'articles',
        'client': client,
        'orders': orders,

    }

    return render(request, 'online_store/orders.html', context)


def list_client_items(request, client_id):
    client = get_object_or_404(Client, pk=client_id)
    period = request.GET.get('period')
    selected_period = int(period) if period else None

    if selected_period == 7:
        date_from = datetime.now() - timedelta(days=7)
    elif selected_period == 30:
        date_from = datetime.now() - timedelta(days=30)
    elif selected_period == 365:
        date_from = datetime.now() - timedelta(days=365)
    else:
        date_from = None

    if date_from:
        items = OrderItem.objects.filter(
            order__customer=client,
            order__date_ordered__gte=date_from,
        ).order_by('-order__date_ordered')
    else:
        items = None

    context = {
        'client': client,
        'items': items,
        'selected_period': selected_period,
    }

    return render(request, 'online_store/client.html', context)


def add_image_product(request, product_id):
    product = Product.objects.filter(pk=product_id).first()
    if request.method == 'POST':
        form = forms.AddImageProduct(request.POST, request.FILES)
        if form.is_valid():
            photo = form.cleaned_data['photo']

            product.photo = photo
            product.save()
    else:
        form = forms.AddImageProduct()

    return render(request, 'online_store/add_image_product.html', {'form': form})

seminars/seminars_project/online_store/templates/online_store/add_image_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>{{ form.as_table }}</table>
        <input type="submit" value="enter" >
    </form>
</body>
</html>

seminars/seminars_project/online_store/templates/online_store/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Title {% endblock %}</title>
</head>
<body>
    <header>
        <h2>Интернет магазин</h2>
    </header>
    {% block content %} в разработке {% endblock %}
<footer>
    <h2> Разработан: Писарев Николай </h2>
</footer>
</body>
</html>

seminars/seminars_project/online_store/templates/online_store/client.html
{% extends 'online_store/base.html' %}

{% block content %}
    <h1>Заказанные товары: {{ client.name }}</h1>

    <form method="get">
        <input type="submit" name="period" value="7" />
        <input type="submit" name="period" value="30" />
        <input type="submit" name="period" value="365" />
    </form>

    {% if items %}
        <h2>Список товаров за последние {{ selected_period }} дней:</h2>
        <ul>
            {% for item in items %}
                <li>{{ item.product.name }}, категория: {{ item.product.category }}, дата заказа: {{ item.order.date_ordered }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>В данный период клиент не заказывал товаров.</p>
    {% endif %}
{% endblock %}

seminars/seminars_project/online_store/templates/online_store/orders.html
{% extends 'online_store/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <h1>Заказы клиента: {{ client.name }}</h1>

    <table>
        <thead>
            <tr>
                <th>Номер заказа</th>
                <th>Дата заказа</th>
                <th>Общая стоимость</th>
                <th>Товары</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <td>{{ order.pk }}</td>
                    <td>{{ order.date_ordered }}</td>
                    <td>{{ order.total_price }}</td>
                    <td>
                        <ul>
                            {% for item in order.orderitem_set.all %}
                                <li>{{ item.quantity }}x {{ item.product.name }} по {{ item.price }} руб.</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}